simulate tests and updated templates
karpatkey/roles_royce pull request #110
Opened 2023-11-27 21:48 UTC by Richymaestro

2023-11-29 19:02 UTC, sgzerbo requested changes

2023-11-29 19:02 UTC, sgzerbo commented on roles_royce/applications/panic_button_app/config/templates/aura_template.json
> +      "description": "Unstake BPT from Aura and exit pool on Balancer with Proportional exit. (Recovery Mode)",
Remove fullstop at the end, or add fullstops at the end of all descriptions. Plus, "(Recovery Mode)" should come before the fullstop

2023-11-29 19:54 UTC, Richymaestro commented on tests/applications/panic_button_app/test_simulate.py
> +    assert main.returncode == 0
This is right, the script is properly executed (hence the returncode 0), but it gets an error because the HTTP port times out (have to figure out why) and that is captured in the line 'except Exception as e: with status 500'

2023-11-29 19:55 UTC, Richymaestro commented on roles_royce/applications/panic_button_app/config/templates/aura_template.json
> +      "description": "Unstake BPT from Aura and exit pool on Balancer with Proportional exit. (Recovery Mode)",
I will check the templates again and make it more clear

2024-05-30 11:33 UTC, ismaelga commented
close?

2024-10-04 11:47 UTC, Richymaestro commented
not needed anymore, moved to other repo

2024-10-04 11:47 UTC, closed without merging